projectcalico/vpp-dataplane

- calico-vpp-agent/config/config.go
- calico-vpp-agent/routing/bgp_watcher.go
- calico-vpp-agent/routing/prefix_watcher.go
- calico-vpp-agent/routing/routing_server.go
- calico-vpp-agent/services/service_server.go
- test/baremetal/kubeadm/ClusterJoinConfiguration.template.yaml
- test/baremetal/kubeadm/ClusterNewConfiguration.template.yaml
- test/baremetal/orch.sh
- test/baremetal/provision.sh
- test/scripts/perftest/iperf/test.yaml
- test/scripts/vppdev.sh
- vpp-manager/README.md
- vpp-manager/main.go
- yaml/overlays/dev/kustomize.sh
For now only full dualstack has been tested (services `v4` & `v6` with `v4` & `v6` podIPs and `v4` & `v6` nodeIPs)
Other combinations will need adding support for NAT46 in vpp plugin
> Add dualstack support

- calico-vpp-agent/common/common.go
- calico-vpp-agent/routing/connectivity/connectivity.go
- calico-vpp-agent/routing/connectivity/flat.go
- calico-vpp-agent/routing/connectivity/ipip.go
- calico-vpp-agent/routing/connectivity/ipsec.go
- calico-vpp-agent/routing/routing_server.go
- test/scripts/cases.sh
- test/scripts/cases_util.sh
- test/scripts/ci.sh
- test/scripts/ci_util.sh
- test/scripts/shared.sh
* This fixes graceful restart for ipip & ipsec (cache wasn't getting properly cleaned)
* It adds a synchronization mechanism in the case where we need to restart the BGP server
* It adds `ci.sh` and `ci_util.sh` scripts to allow running a ~somewhat rudimentary CI (bash script based...)
* Adds new tests `(flat ip, ipip, ipsec) x (ipv4, ipv6)` and `(nodeports, natOutgoing) x (ipv4, ipv6)`
> Fix graceful restart & add more tests and CI

- calico-vpp-agent/cmd/calico_vpp_dataplane.go
- calico-vpp-agent/cni/cni_file_storage.go
- calico-vpp-agent/cni/cni_server.go
- calico-vpp-agent/cni/network_vpp.go
- calico-vpp-agent/common/common.go
- calico-vpp-agent/config/config.go
- calico-vpp-agent/routing/routing_server.go
- calico-vpp-agent/services/service_server.go
Upon startup
* Services poll the k8 api and re-create the missing ones
* Container state is persisted in a flat file, that's read on startup
* Peering info should catch up with BGP
> Support calico-vpp-agent restart

- .gitignore
- calico-vpp-agent/services/service_server.go
- test/scripts/shared.sh
- test/scripts/vppdev.sh
- vpp-manager/Makefile
- vpp-manager/images/dev/Dockerfile
- vpp-manager/images/ubuntu/Dockerfile
- yaml/base/calico-vpp.yaml
- yaml/overlays/dev/kustomize.sh
calivppctl should be shipped in vpp images and installed with :
* With curl 
````bash
curl https://raw.githubusercontent.com/projectcalico/vpp-dataplane/master/test/scripts/vppdev.sh \
| sudo tee /usr/bin/calivppctl
sudo chmod +x /usr/bin/calivppctl
````
* With docker (and a cluster with calico-vpp runnning)
````bash
sudo docker cp $(docker ps | grep vpp_calico-vpp | awk '{ print $1 }'):/usr/bin/calivppctl /usr/bin/calivppctl
````
* With kubectl (and a cluster with calico-vpp runnning)
````bash
kubectl -n kube-system exec -it \
$(kubectl -n kube-system get pods -o wide | grep calico-vpp-node- | awk '{ print $1 }' | head -1) \
-c vpp -- cat /usr/bin/calivppctl | sudo tee /usr/bin/calivppctl > /dev/null
sudo chmod +x /usr/bin/calivppctl
````
Signed-off-by: Nathan Skrzypczak …
> Make calivppctl more user-friendly

- vpp-manager/Makefile
- vpp-manager/images/ubuntu/Dockerfile
Those are now needed to be able to inspect corefiles generated on VPP crash.
It's debatable whether or not we want to ship them with release images, 
but in an alpha/beta stage, it might be best including them for the sake of 
user-friendlyness when reporting issues.
> Add debug symbols to release container

- vpp-manager/main.go
- vpp-manager/pool_sync.go
- vpp-manager/uplink/avf.go
- vpp-manager/utils/utils.go
* When using avf uplink, vpp-manager will now :
* if the interface is a PF without a VF, create a VF + generate a mac for it. Addresses will be taken on the PF in linux
* if the interface is a PF with an existing VF, it will use the first vf and its mac. ip addresses & routes taken on the linux PF
* if the interface is a VF, it will use it as is
* This also fixes the broken pipe signal being mishandled & forwarded to VPP
> Fix AVF uplink & broken pipe

- vpp-manager/vpp_runner.go
- vpplink/routes.go
- vpplink/types/route.go
Set ip4 flow hash only if specifying multiple addresses
Don't use ip6 flow hash as it isn't used & breaks in current vpp
> vpp-manager: Fix ip6 flow hash

- vpp-manager/uplink/dpdk.go
- vpp-manager/utils/utils.go
- vpplink/binapi/vpp_clone_current.sh
- vpplink/ipip.go
- yaml/overlays/dev/kustomize.sh
* in dpdk, check if interface was renamed in the process
* add af-packet interrupt patch
* autodetect = vpptap0 in dev
> Usability fixes [dpdk, af-packet]

- calico-vpp-agent/routing/felix_config_watcher.go
- vpp-manager/config/config.go
- vpp-manager/images/init-eks/init_eks.sh
- vpp-manager/pool_sync.go
- vpp-manager/startup/startup.go
- vpp-manager/uplink/af_xdp.go
- vpp-manager/vpp_runner.go
- vpplink/interfaces.go
- yaml/base/calico-patch.yaml
- yaml/overlays/eks-dpdk/eks-config.yaml
- yaml/overlays/eks-dpdk/eks-init.yaml
- yaml/overlays/eks/eks-config.yaml
````bash
export CLUSTER_NAME=test-dpdk
eksctl create cluster --name=$CLUSTER_NAME --version=1.17 --without-nodegroup --auto-kubeconfig
kubectl --kubeconfig delete daemonset -n kube-system aws-node
kubectl kustomize ./yaml/overlays/eks-dpdk | kubectl --kubeconfig apply -f -
eksctl create nodegroup --cluster $CLUSTER_NAME --nodes 2 --ssh-access --ssh-public-key=<MYKEY>
````
✅ kube-system pods
✅ user pods
✅ iperf node-node
✅ nslookup
✅ curl http://
❓ remove / reinstall
````bash
export CLUSTER_NAME=test-dpdk
eksctl create cluster --name=$CLUSTER_NAME --version=1.17 --without-nodegroup --auto-kubeconfig
kubectl --kubeconfig delete daemonset -n kube-system aws-node
kubectl kustomize ./yaml/overlays/eks | kubectl --kubeconfig apply -f -
eksctl create nodegroup --cluster $CLUSTER_NAME --nodes 2 …
```
> yaml: Fix EKS default yaml

- vpp-manager/config/config.go
- vpp-manager/pool_sync.go
- vpp-manager/startup/startup.go
- vpp-manager/uplink/af_xdp.go
- vpp-manager/vpp_runner.go
- vpplink/interfaces.go
This also renames `TapMtu` to `UserspecifiedMtu` for clarity
and adds a dedicated function for getting the Mtu
> vpp-manager: Set uplink MTU to host val

- calico-vpp-agent/cmd/calico_vpp_dataplane.go
- calico-vpp-agent/cni/network_vpp.go
- calico-vpp-agent/common/common.go
- calico-vpp-agent/routing/connectivity/ipip.go
- calico-vpp-agent/routing/connectivity/ipsec.go
- calico-vpp-agent/routing/connectivity/vxlan.go
- calico-vpp-agent/routing/routing_server.go
- vpplink/binapi/vpp_clone_current.sh
- vpplink/interfaces.go
- vpplink/ip.go
- vpplink/routes.go
This also includes a couple fixes in VPP:
- One for a crash in the checksum computation
- One that clears all established sessions when reconfiguring policies on an interface
> routing: send pod->node traffic into tunnels

- vpp-manager/config/config.go
- vpp-manager/hooks/hooks.go
- vpp-manager/main.go
- vpp-manager/startup/startup.go
- vpp-manager/uplink/common.go
- vpp-manager/uplink/dpdk.go
- vpp-manager/utils/utils.go
- vpp-manager/vpp_runner.go
- yaml/base/calico.yaml
- yaml/generated/calico-vpp-dpdk.yaml
- yaml/generated/calico-vpp-eks-dpdk.yaml
- yaml/generated/calico-vpp-eks.yaml
- yaml/generated/calico-vpp-nohuge.yaml
- yaml/generated/calico-vpp.yaml
- yaml/overlays/eks-dpdk/eks-config.yaml
- yaml/overlays/eks-dpdk/kustomization.yaml
- yaml/overlays/eks/eks-config.yaml
Instability seems to be related to dhclient, which doesn't get restarted after uplink swap
and fails to send DHCP broadcasts.
Issuing a `systemctl restart network` after uplink swap solves the issue, even if not ideal
````bash
journalctl -u network.service
...
dhclient[2767]: DHCPREQUEST on eth0 to 192.168.32.1 port 67 (xid=0x7c1b4f61)
dhclient[2767]: DHCPREQUEST on eth0 to 192.168.32.1 port 67 (xid=0x7c1b4f61)
dhclient[2767]: DHCPREQUEST on eth0 to 192.168.32.1 port 67 (xid=0x7c1b4f61)
dhclient[2767]: DHCPREQUEST on eth0 to 255.255.255.255 port 67 (xid=0x7c1b4f61)
dhclient[2767]: send_packet: No such device or address
dhclient[2767]: dhclient.c:2736: Failed to send 300 byte long packet over eth0 interface.
...
````
> Fix eks instability

- calico-vpp-agent/policy/policy_server.go
- calico-vpp-agent/routing/watchers/nodes_watcher.go
- calico-vpp-agent/services/service_server.go
This can happen if we start Felix without any address configured.
Typically a misconfigured v6 cluster with no v4 addresses, but felix
still searching for one.
> agent: Fix no BGP config found

- vpplink/binapi/vpp_clone_current.sh
- yaml/generated/calico-vpp-eks-dpdk.yaml
- yaml/overlays/eks-dpdk/eks-config.yaml
Cherry-pick the dpdk-21.05 ena interrupt support patch which is based on the
following patch:
https://patches.dpdk.org/project/dpdk/patch/20210713154118.32111-5-mk@semihalf.com/
> dpdk-21.05 ena interrupt support

- calico-vpp-agent/cni/network_vpp.go
- calico-vpp-agent/cni/pod_interface/memif.go
- calico-vpp-agent/routing/routing_server.go
- vpplink/binapi/vpp_clone_current.sh
- vpplink/binapi/vppapi/af_xdp/af_xdp.ba.go
- vpplink/binapi/vppapi/af_xdp/af_xdp_rpc.ba.go
- vpplink/binapi/vppapi/generate.log
- vpplink/binapi/vppapi/interface/interface.ba.go
- vpplink/binapi/vppapi/interface/interface_rpc.ba.go
- vpplink/binapi/vppapi/memif/memif.ba.go
- vpplink/binapi/vppapi/memif/memif_rpc.ba.go
- vpplink/binapi/vppapi/tapv2/tapv2.ba.go
- vpplink/binapi/vppapi/tapv2/tapv2_rpc.ba.go
- vpplink/cnat.go
- vpplink/helpers.go
- vpplink/interfaces.go
- vpplink/memif.go
- vpplink/routes.go
- vpplink/session.go
This updates the API for creating memif sockets per changes required for upstream
- memif socket IDs are now allocated opportunistically walking the hash
- netns name is part of the socket name
> Integrate updated memif API

- vpp-manager/config/config.go
- vpp-manager/pool_sync.go
- vpp-manager/uplink/af_packet.go
- vpp-manager/uplink/af_xdp.go
- vpp-manager/uplink/avf.go
- vpp-manager/uplink/common.go
- vpp-manager/uplink/default.go
- vpp-manager/uplink/dpdk.go
- vpp-manager/uplink/rdma.go
- vpp-manager/uplink/virtio.go
- vpp-manager/uplink/vmxnet3.go
- vpp-manager/utils/utils.go
- vpp-manager/vpp_runner.go
It appears process termination does delete veth interfaces put in its net namespace - 
which is not true for physical interfaces.
This makes the parking netns used for the uplink interfaces taken by VPP a persistant one, 
created with iproute2.
> vpp-manager: Make vpp own netns persistant

- vpplink/vxlan.go
This fixes VXLAN due to a patch in VPP changing a boolean by its opposite in the API.
> agent: fix VXLAN due to api change

- calico-vpp-agent/cni/network_vpp.go
- calico-vpp-agent/policy/messages.go
- calico-vpp-agent/policy/policy_server.go
- calico-vpp-agent/watchers/peers_watcher.go
- vpplink/binapi/vpp_clone_current.sh
- vpplink/binapi/vppapi/capo/capo.ba.go
- vpplink/binapi/vppapi/generate.log
This makes the policy log slightly better (less logs for unhandled messages, more for policy changes)
and integrates [0] which makes VPP debug CLIs in capo a bit better, and most importantly 
initialize the enum in the api to 0, as this was not correctly reflected in the generated bindings
[0] https://gerrit.fd.io/r/c/vpp/+/28513/24..25
> agent: better policy log & enum fix

- vpp-manager/config/config.go
- vpp-manager/startup/startup.go
- vpp-manager/utils/utils.go
Allow to leverage node annotaions in vpp's config file
templating. This can be used to have as vpp.conf
````
cpu {
main-core __NODE_ANNOTATION:cni.projectcalico.org/vpp.main-core__
}
````
The value coming from:
````
kubectl annotate node <somenode> cni.projectcalico.org/vpp.main-core=123
````
> vpp-manager: leverage node annot in config template

- Makefile
The calico user docs make use of {{page.vppbranch}} var which must point to the
release of calico/vpp corresponding to the calico release. This var in turn is
defined as "vppbranch" var in
[https://github.com/projectcalico/calico/blob/<release>/calico/_config.yml](https://github.com/projectcalico/calico/blob/%3Crelease%3E/calico/_config.yml)
In general,
1. vppbranch=master for the master branch of calico
2. vppbranch=master after a calico release and until a corresponding
calico/vpp release
3. vppbranch=<RELEASE TAG> for a calico release with a corresponding
calico/vpp release
If "vppbranch" is left dangling after a calico/vpp release then it can
cause the user docs to be broken. An example being the 0.18.0 release
which left "vppbranch" pointing at "master" and as a result the calico …
> Makefile: add a reminder to update {{page.vppbranch}} var

- calico-vpp-agent/cmd/calico_vpp_dataplane.go
- calico-vpp-agent/cni/cni_server.go
- calico-vpp-agent/cni/pod_interface/common.go
- calico-vpp-agent/common/common.go
- calico-vpp-agent/connectivity/connectivity.go
- calico-vpp-agent/connectivity/connectivity_server.go
- calico-vpp-agent/connectivity/flat.go
- calico-vpp-agent/connectivity/ipip.go
- calico-vpp-agent/connectivity/ipsec.go
- calico-vpp-agent/connectivity/srv6.go
- calico-vpp-agent/connectivity/vxlan.go
- calico-vpp-agent/connectivity/wireguard.go
- calico-vpp-agent/policy/policy_server.go
- calico-vpp-agent/prometheus/prometheus.go
- calico-vpp-agent/routing/bgp_watcher.go
- calico-vpp-agent/routing/routing_server.go
- calico-vpp-agent/services/service_server.go
- calico-vpp-agent/watchers/bgp_configuration_watcher.go
- calico-vpp-agent/watchers/ipam.go
- calico-vpp-agent/watchers/kernel_watcher.go
- calico-vpp-agent/watchers/nodes_watcher.go
- calico-vpp-agent/watchers/peers_watcher.go
- calico-vpp-agent/watchers/prefix_watcher.go
- calico-vpp-agent/watchers/srv6_localsid_watcher.go
- vpplink/interfaces.go
This PR changes the behavior of the agent on VPP's fault (SIGUSR1) to exit, and wait to be restarted by the k8s scheduler. This simplifies the state-reconciliation logic, most importantly preventing re-programming of VPP to trigger another segfault and end up in semi-programmed state.
> Make agent fate share on VPP fault

- calico-vpp-agent/policy/policy_server.go
Return an error when the policy creation fails,
otherwise we risk a NPE on updates that depend
on the server properties they fill.
Also add the createFailSafePolicies that went
missing with #341
> agent: fix policies init

- calico-vpp-agent/policy/policy_server.go
It can apparently happen that some fields are missing
when receiving the felixConfig via the socket.
Recreating the felixConfig object from scratch
each time resets the values to their default when
the fields are not present
> agent: recreate felixConfig for missing fields

- calico-vpp-agent/cni/network_vpp.go
- calico-vpp-agent/cni/network_vpp_routes.go
- calico-vpp-agent/cni/pod_interface/common.go
- calico-vpp-agent/cni/pod_interface/loopback.go
- calico-vpp-agent/cni/storage/storage.go
- vpplink/helpers.go
- vpplink/ip.go
This make the VRF tag be a hash (netns, ipversion),
followed by the ip version, and the netns basename truncated to 63 chars
Matching existing VRFs is then done based on this tag.
This allows to keep a user friendly display in the debug CLI
while preventing toe stepping on restarts (where existing VrfIds
get reallocated)
> agent: better VRF tags

- calico-vpp-agent/cni/cni_server.go
- calico-vpp-agent/cni/storage/storage.go
We were passing a pointer on the loop iterator
in the AddVppInterface function, which ended up
down the event chan. This corrupted the swIfIndices
passed to the policy server on state reconciliation
> agent: fix CNI pointer on state-recon

- calico-vpp-agent/cni/cni_server.go
- calico-vpp-agent/cni/network_vpp.go
- calico-vpp-agent/cni/storage/storage.go
It can happen that having already configured an address
for a pod in VPP, we receive an add for a new pod with this
same address. The deletion notification for the old pod
comes only later, removing the main VRF route for the new
pod.
This patch ensures that when we adding the second pod we
first make sure to clean up existing pods with this address.
> agent: clean conflicting IPs on pod add

- calico-vpp-agent/cni/network_vpp_hostports.go
- calico-vpp-agent/common/common.go
- calico-vpp-agent/services/service_handler.go
- calico-vpp-agent/services/service_server.go
- vpplink/types/cnat.go
Resolve services to cnatEntries as soon as possible
to make computing the difference in case of an update
easier.
This also contains a fix : when a delete was preceded
by an update setting the list of backends to [] we were
not actually deleting the cnat entry.
> agent: refactor services

- vpp-manager/uplink/default.go
The uplink driver load checking missed the 'uio_pci_generic' driver.
Signed-off-by: Haiyue Wang <haiyue.wang@intel.com>
> vpp-manager: fix the uplink driver load checking

- Makefile
This patch adds a `major.minor` tag on the HEAD we are currently pointing to when creating the release branche.
This allows to have the tags being present in the main tree, for easier history exploration.
> Add release tag to master

- Makefile
- vpp-manager/images/ubuntu-build/Dockerfile
- vpplink/af_packet.go
- vpplink/binapi/vpp_clone_current.sh
- vpplink/binapi/vppapi/af_packet/af_packet.ba.go
- vpplink/binapi/vppapi/af_packet/af_packet_rpc.ba.go
- vpplink/binapi/vppapi/generate.log
- vpplink/binapi/vppapi/ipsec/ipsec.ba.go
- vpplink/binapi/vppapi/ipsec/ipsec_rpc.ba.go
- vpplink/binapi/vppapi/ipsec_types/ipsec_types.ba.go
- vpplink/binapi/vppapi/memclnt/memclnt.ba.go
- vpplink/binapi/vppapi/memclnt/memclnt_rpc.ba.go
- vpplink/binapi/vppapi/nat44_ed/nat44_ed.ba.go
- vpplink/binapi/vppapi/nat44_ed/nat44_ed_rpc.ba.go
- vpplink/binapi/vppapi/punt/punt.ba.go
- vpplink/binapi/vppapi/session/session.ba.go
- vpplink/binapi/vppapi/sr/sr.ba.go
- vpplink/binapi/vppapi/sr/sr_rpc.ba.go
- vpplink/binapi/vppapi/urpf/urpf.ba.go
- vpplink/binapi/vppapi/wireguard/wireguard.ba.go
- vpplink/urpf.go
- yaml/overlays/dev/kustomize.sh
This patch bumps (again) VPP to its latest version. Currently known issues doing this are :
- checksum are not properly computed on kind. Traffic from tap0 (traffic originated by the node) gets dropped in linux with a wrong checksum
- af-packet API has changed and needs adaptation.
> Bump VPP to latest

- Makefile
- config/startup/startup.go
- config/startup/startup_test.go
This patch fixes a segfault happening when the corefile was not specified in the environment variable. It also tries to improve the logic a bit and adds a test for this function.
Additionnally this patch also enables running tests in `make test` and in the CI. This should not include the integration tests that require the envvar INTEGRATION_TEST to be set.
> vpp-manager: Fix corefile cleanup

- config/config/config.go
- vpp-manager/uplink/af_packet.go
- vpp-manager/uplink/af_xdp.go
- vpp-manager/uplink/avf.go
- vpp-manager/uplink/common.go
- vpp-manager/uplink/default.go
- vpp-manager/uplink/dpdk.go
- vpp-manager/uplink/rdma.go
- vpp-manager/uplink/virtio.go
- vpp-manager/uplink/vmxnet3.go
- vpp-manager/vpp_runner.go
- vpplink/af_packet.go
- vpplink/types/vpp_interface.go
This adds an annotation map on the uplinkConfiguration object in the json definition allowing to change v2/v3 version for af_packet and the use of qdisc bypass or not.
We now default to qdisc bypass disables as this seems to be related to issues on EC2. But this is now exposed in the configuration.
> vpp-manager: Add uplink annotations, default disable qdisc bypass

- test/kind/Makefile
- test/kind/new_cluster.sh
This patch make the kind-new-cluster directive use a N_KIND_WORKERS variable, defaulting to 3 workers (so 4 nodes)
> kind: use default num workers

- vpplink/binapi/patches/0001-pbl-Port-based-balancer.patch
- vpplink/binapi/patches/0002-cnat-WIP-no-k8s-maglev-from-pods.patch
- vpplink/binapi/patches/0003-acl-acl-plugin-custom-policies.patch
- vpplink/binapi/patches/0004-capo-Calico-Policies-plugin.patch
- vpplink/binapi/vpp_clone_current.sh
- vpplink/binapi/vppapi/capo/capo.ba.go
- vpplink/binapi/vppapi/generate.log
- vpplink/capo.go
- vpplink/types/capo.go
This patch changes the semantics for capo policies and rules,
it makes it so that VPP debug CLI & code uses rx/tx when refering
to packets comming into VPP (rx) or out of VPP (tx).
In Calio, the semantic is the opposite, the point of view taken by
the implementation is that of a container. Hence the traffic
coming out of VPP will be (ingress), and that coming into VPP
will be (egress).
> vpp: use capo RX/TX in vpp & ingress/egress in Calico.

- vpplink/binapi/patches/0004-capo-Calico-Policies-plugin.patch
- vpplink/binapi/vppapi/capo/capo.ba.go
- vpplink/binapi/vppapi/generate.log
This patch adds support for inverting RX & TX in the capo_interface
definition. We can now specify when mapping a policy to an interface
whether RX rules should be applied on RX traffic (from VPP's standpoint)
or inverted, i.e. applied on TX traffic.
> vpp: Support policy RX/TX inversion in capo

- yaml/base/calico-vpp-daemonset.yaml
- yaml/generated/calico-vpp-dpdk.yaml
- yaml/generated/calico-vpp-eks-dpdk.yaml
- yaml/generated/calico-vpp-eks.yaml
- yaml/generated/calico-vpp-kind.yaml
- yaml/generated/calico-vpp-nohuge.yaml
- yaml/generated/calico-vpp.yaml
- yaml/overlays/default-huge/default-huge.yaml
- yaml/overlays/dpdk/dpdk.yaml
- yaml/overlays/eks-dpdk/eks-config.yaml
- yaml/overlays/eks/eks-config.yaml
Fix the yamls which got messed up post the config changes.
1. Add back the missing fields for eks
2. Set vppDriver explicitly per individual manifests
> Fix manifest yamls

- vpplink/binapi/vpp_clone_current.sh
- vpplink/binapi/vppapi/generate.log
- vpplink/binapi/vppapi/ipsec/ipsec.ba.go
- vpplink/binapi/vppapi/ipsec/ipsec_rpc.ba.go
This upgrade of VPP's version contains fixes for af_packet. Notable included fixes are : 8a0fd0669 - af_packet: add the missing header-len for packets with checksum offload 6a07348f4 - pci: add option to force uio binding
bca76580b - af_packet: move to plugin
And a cherry pick of a pending patch
git_cherry_pick refs/changes/31/37931/1 # 37931: ip: add the missing offload check | https://gerrit.fd.io/r/c/vpp/+/37931
> vpp: upgrade to 8a0fd0669047c90d410d2ed5cb508bfe778b932a (19 jan 23)

- calico-vpp-agent/watchers/net_watcher.go
- vpp-manager/Makefile
- vpp-manager/images/ubuntu-build/build_script.sh
- yaml/overlays/dev/kustomize.sh
This patch enables get_feature_gates which was missing in kustomize.sh
It also adds a make rebuild-vpp target in vpp-manager to do a local rebuild of VPP whithout the debs to shorten build iterations in dev
This also adds more context to the errors returned by the net_watcher.
> misc: dev env improvements

- config/config.go
- config/config_parse.go
- config/config_test.go
This patch makes it so that JsonEnvVars implementing Validate() error will also have their method called even if the envvar is not defined. This allows to set defaults at the start of the program and avoid NPE when the propertie's type is a pointer.
> config: also validate missing jsonEnvVars

- calico-vpp-agent/cni/cni_pod_test.go
- calico-vpp-agent/cni/pod_interface/memif.go
- calico-vpp-agent/policy/host_endpoint.go
- calico-vpp-agent/policy/policy_server.go
- calico-vpp-agent/policy/workload_endpoint.go
no need to remove leaking rules as they are automatically deleted when no policy uses them anymore.
However some policies we recreate are leaking so needed to remove them
> agent: remove leaking policies in system policies

- vpp-manager/uplink/dpdk.go
- vpplink/types/errors.go
- vpplink/types/errors_test.go
> vpp-manager: Only warn if setting the DPDK mac in VPP is unsupported

- calico-vpp-agent/policy/policy_server.go
- vpp-manager/uplink/dpdk.go
- snat: fix exclusions config
- dpdk: more logs
Previously, packets coming from one IP Pool with Masquerade = true to an IP Pool with Masquerade = False would get source-nat'ed.
Worse, packets coming from a pool with Masquerade = True to a pool with Masquerade = False would not get SNAT'ed, but the return packets would be, breaking the connection.
> Fix internal SNAT

- calico-vpp-agent/cni/network_vpp_routes.go
- calico-vpp-agent/common/common.go
- vpp-manager/utils/utils.go
- vpplink/routes.go
- vpplink/types/route.go
This patch forwards the multicast traffic originiating from the pods to the calico-pods-46 VRF, so that this traffic might be configured by users without knowleged of the pod's VRF table_id.
> vpp: foward mcast traffic to calico-pods-46

- Makefile
- calico-vpp-agent/Makefile
- calico-vpp-agent/cmd/api-proxy/Makefile
- multinet-monitor/Makefile
- vpp-manager/Makefile
This patch fixes the api-proxy build that could result in a mismatch between the glibc version used for linking when building and the one used in the run environment (i.e. the calico container where the image is run).
This also makes dev build produce :latest images in addition to the new :commit-hash tags, to maintain old behavior.
> build: Fix api-proxy build and dev build.

- calico-vpp-agent/cmd/calico_vpp_dataplane.go
- calico-vpp-agent/connectivity/vxlan.go
- calico-vpp-agent/watchers/net_watcher.go
A bug appears when you: add a network, add pods in it (vxlan triggered), then delete the pods and network, then re-add it.
There is a leftover state of a configured loopback in vxlan provider that causes this.
Solution is to use the map that is updated when the network is created/deleted.
> multinet: fix loopbacks leftover state in vxlan provider

- .ci/common.mk
- Makefile
- test/integration-tests/run-tests.sh
This default to WITH_GDB=yes to have GDB present in all the build as it is low footprint (~40Mb), and quite handy to troubleshoot VPP related issues.
This also makes the integration-tests script inherit the TAG from the makefile .ci/common.mk
> build: pass TAG to integration tests & default to WITH_GDB=yes

- vpplink/binapi/patches/0001-pbl-Port-based-balancer.patch
- vpplink/binapi/patches/0002-cnat-WIP-no-k8s-maglev-from-pods.patch
- vpplink/binapi/patches/0003-acl-acl-plugin-custom-policies.patch
- vpplink/binapi/patches/0004-capo-Calico-Policies-plugin.patch
- vpplink/binapi/patches/0005-memif-fix-socket-name-null-termination.patch
- vpplink/binapi/vpp_clone_current.sh
The socket name was not properly null terminated when passed via the API. This should go away with the next rebase of VPP.
> vpp: memif, fix null termination of socket name

- .gitignore
- calico-vpp-agent/Dockerfile
- calico-vpp-agent/Makefile
- calico-vpp-agent/cni/pod_annotations.go
- config/config.go
This patch moves agent binaries to bin/ instead of the same folder as their sources.
> refact: move agent binaries to bin/

- docs/README.md
"Multinet feature documetation" item is pointing at the migrate_to_calicovpp.md while the "Existing Calico cluster migration" item is pointing at multinet.md :)
> fix typos and incorrect links in docs/README

- calico-vpp-agent/cmd/calico_vpp_dataplane.go
- config/config.go
In the case one of the goroutine fails to gracefully terminate, we add a failsafe condition to panic after a configurable amount of time after the tomb has returned.
It defaults to 10 seconds.
> agent: Add failsafe termination after 10s

- calico-vpp-agent/cni/cni_server.go
Fix deadlock due to a misplaced break which was supposed to break out of the for loop but instead it broke out of the inner select
> cni: fix for deadlock

- calico-vpp-agent/policy/messages.go
Do not print an error message when we receive an error message in the felix-dataplane.sock message reader.
We keep a debug message for debuggability.
> agent: Do not print error on EOF

- calico-vpp-agent/watchers/net_watcher.go
- test/yaml/multinet/network.yaml
- test/yaml/multinet/pod-memif.yaml
Prior to this patch we were not correctly restarting the api watcher
for the network objects, ie when the watcher breaks network server in
calicovpp agent logs warning or returns an error and we only recover if
we restart agent. This patch allows to restart the watcher if it breaks,
while keeping the resource version to continue watching.
> agent: fix network watcher

- calico-vpp-agent/cmd/calico_vpp_dataplane.go
- calico-vpp-agent/cni/cni_server.go
this fixes the case where a host port is created without explicit host ip
node ip is used as host ip in that case
> agent: host port per default uses node ip as host ip

- yaml/components/ipsec/README.md
- yaml/components/ipsec/ipsec.yaml
- yaml/components/ipsec/kustomization.yaml
When transitionning to the new Config syntax in v3.25.0 we forgot to update the ipsec component.
This patch addresses this
This is linked to the following docs update on tigera/docs https://github.com/tigera/docs/pull/774
> yaml: Fix ipsec installation component

- config/config.go
- vpp-manager/startup/startup.go
- vpp-manager/uplink/dpdk.go
- vpp-manager/uplink/virtio.go
- vpp-manager/uplink/vmxnet3.go
- vpp-manager/utils/utils.go
This patch fixes the detection of unsafe iommu being available, initially enabled or disabled. It makes sure the available drivers properly restore the initial state, and that we do not try to enable unsafe-iommu when no iommu is available.
> vpp-manager: Fix unsafe iommu detection & enabling

- calico-vpp-agent/services/service_handler.go
We snat when endpoint is not local, no need to do it when it is local.
This is for the returned traffic to pass by the node.
> agent: fix nodeport service snat

- vpplink/generated/vpp_clone_current.sh
This integrates a patch from VPP, that fixes the checksum calculation in cnat. This fix addresses a connectivity failure that showed up in eks dpdk scenario.
> fix cnat csum

- docs/kind.md
This patch adds documentation on how to set up a kind cluster with calico/vpp & multinet installed, without requiring to build VPP locally or to have the whole repository cloned locally.
This should work without requiring to run any remote script.
> docs: Add kind doc for users

- Makefile
- docs/kind.md
- docs/multinet.md
multus master does not work anymore in our case, this forces an older version by a commit hash
> fix multus version used in docs

- calico-vpp-agent/cni/cni_server.go
- config/config.go
- vpp-manager/startup/startup.go
- vpp-manager/uplink/default.go
- vpp-manager/uplink/dpdk.go
- vpp-manager/utils/utils.go
- vpp-manager/vpp_runner.go
This patch simplifies the way we handle the punt routes when routing for-me traffic VPP cannot handle to the host. Previously, we were using different fake gateways for ip4 & ip6. We now use the ip4 indirection in both cases.
We also generate different hardware addresses using the uplink order in the configuration.
Finally, we also make the isMain parameter public in the config.
> simplify punt fake gateway

- calico-vpp-agent/services/service.go
- calico-vpp-agent/services/service_handler.go
- calico-vpp-agent/services/service_server.go
- vpplink/cnat.go
- vpplink/generated/bindings/cnat/cnat.ba.go
- vpplink/generated/generate.log
- vpplink/generated/vpp_clone_current.sh
- vpplink/types/cnat.go
This patch uses the newly introduced field in cnat translation vpp api to pass ecmp hashconfig defined by annotations in services.
> vpp: pass hashconfig to vpp for service annotations

- yaml/platforms/openshift/04-calico-vpp-nohuge.yaml
NetworkManager makes no attempt to renew dhcp lease when the default dhcp lease time of 60 mins expires resulting in the wipe out of the node's ip address. This fix coerces NM to keep trying to renew the lease indefinitely so that node always has its ip address intact as long as vpp is running.
> openshift: dhcp lease timeout issue

- yaml/platforms/openshift/00-namespace-calico-vpp-dataplane.yaml
Openshift has pod security admission enabled by default. Adding the required labels.
> openshift: add podSecurity labels

- calico-vpp-agent/services/service_handler.go
It can happen that service IPs are nil when the node does not return an ip6 or an ip4. This patch prevents these making it into the cnat.
> fix nodeIP nil in cnat services

- vpplink/generated/generate.log
- vpplink/generated/vpp_clone_current.sh
This patch cherry picks two cnat patches that aim at
- fixing a segfault in the fib display when entries are leftover
- address a cleanup issue in the cnat that leaks LB objects, so also fib entries, ipip adjacencies, etc...
> cnat: fix fib entry cleanup

- calico-vpp-agent/policy/policy_server.go
This patch adds support for setting the .net property when defining
the failsafepolicies in felixconfig. This is a not so well documented
feature that slipped through when aiming for feature parity.
For reference, here is the documentation for [0] felixconfig.
- setting failsafeInboundHostPorts to e.g. {Net: "10.0.0.0/24", ...}
will add a filter for inbound packets for their source prefix to match 10.0.0/24.
- setting failsafeOutboundHostPorts to e.g. {Net: "20.0.0.0/24". ...}
will add a filter for outbound packets for their destination prefix to match 20.0.0/24
[0] https://docs.tigera.io/calico/latest/reference/resources/felixconfig#spec
> Support setting failsafepolicy net

- vpp-manager/vpp_runner.go
This patch removes the closing of the vpplink channel when VPP fails 
to start as if err != nil, vpp will always be nil.
> Fix trying to close vpplink on vpp segfault

- docs/manifest_based_install.md
- yaml/static/README.md
- yaml/static/calico-patch.yaml
- yaml/static/kustomization.yaml
This patch provides a way to generate the static Kubernetes manifest which can be used to install Calico VPP without using operator.
> yaml: add support for generating static Kubernetes manifest

- vpp-manager/images/ubuntu-build/Dockerfile
- vpp-manager/images/ubuntu/Dockerfile
- vpplink/generated/bindings/ikev2/ikev2.ba.go
- vpplink/generated/bindings/ikev2/ikev2_rpc.ba.go
- vpplink/generated/bindings/ikev2_types/ikev2_types.ba.go
- vpplink/generated/bindings/ip/ip.ba.go
- vpplink/generated/bindings/ip/ip_rpc.ba.go
- vpplink/generated/bindings/memclnt/memclnt.ba.go
- vpplink/generated/bindings/memclnt/memclnt_rpc.ba.go
- vpplink/generated/bindings/rdma/rdma.ba.go
- vpplink/generated/bindings/rdma/rdma_rpc.ba.go
- vpplink/generated/bindings/session/session.ba.go
- vpplink/generated/bindings/session/session_rpc.ba.go
- vpplink/generated/bindings/urpf/urpf.ba.go
- vpplink/generated/bindings/urpf/urpf_rpc.ba.go
- vpplink/generated/bindings/virtio/virtio.ba.go
- vpplink/generated/generate.log
- vpplink/generated/patches/0005-partial-revert-arthur-gso.patch
- vpplink/generated/vpp_clone_current.sh
Please refer to the release notes for the list of new features:
https://s3-docs.fd.io/vpp/24.10/aboutvpp/releasenotes/v24.10.html
> vpp: upgrade to v24.10 (30/Oct/24)

- config/config.go
This patch enables memif support by default. Memif support has been in beta for the last two years and has gone through extended testing. As this is a major differentiator for the Calico/VPP integration, 3.29.0 release is a good candidate for making it GA.
Please not that pods will still be required to export the relevant annotation for it to be actually configured by the CNI.
> default to memifEnabled true

- .ci/Dockerfile.depend
- calico-vpp-agent/cmd/calico_vpp_dataplane.go
- calico-vpp-agent/cni/cni_server.go
- calico-vpp-agent/cni/network_vpp.go
- calico-vpp-agent/cni/network_vpp_routes.go
- calico-vpp-agent/connectivity/connectivity_server.go
- calico-vpp-agent/services/service_server.go
- calico-vpp-agent/watchers/bgpfilter_watcher.go
- calico-vpp-agent/watchers/secret_watcher.go
- go.mod
This patch fixes several nitpicks raised by golangcilint 1.64.6 It also bumps the builder image for CI to
- golang 1.24
- golangcilint 1.64.6
> Fixes for golangcilint 1.64.6

- calico-vpp-agent/prometheus/prometheus.go
- config/config.go
This patch adds the ability to configure the polling frequency of prometheus and the port the prometheus server will be listening on and serving metrics under `/metrics`.
This also adds a prometheusEnabled feature gate under
CALICOVPP_FEATURE_GATES to allow disabling the prometheus
exporter if needed.
> Add prometheus config for polling frequency, port & enablement

- docs/corepinning.md
- vpplink/generated/generate.log
- vpplink/generated/vpp.go
- vpplink/generated/vpp_clone_current.sh
This patch adds support in VPP for pinning workers to the CPU cores that are assigned by a static allocator.
When k8s is configured to run with a static allocator [0] and that VPP starts with requests.CPU equal to limits.CPU and both integer numbers.
having VPP configured with
```
cpu {
main-core 0
corelist-workers 2-3
relative
}
```
Will make it so that numbers 0,2,3 do not refer to absolutes CPU IDs but to the 0th, 2nd and 3rd CPU of those allotted by the static core allocator in k8s.
[0] https://kubernetes.io/docs/tasks/administer-cluster/cpu-management-policies/#static-policy
> Add auto corepining path

- calico-vpp-agent/cni/pod_interface/memif.go
- config/config.go
This patch disables memif interface queue spreading on workers by default. Users can enable it again using the debug knob : ``CALICOVPP_DEBUG='{"spreadTxQueuesOnWorkers": true}'``.
This is a consequence of the pinning behaviour of VPP by default. When #queues < #workers, queues are shared by default and pinning them removes their sharing rendering them unusable on some workers.
When #queues > #workers, the extra queues are unpined by default, rendering multi-tx harder to use.
As the latter feature is harder and more niche than the former, we chose to go with a default that suits most usecase, while we work on a better pinning framework.
> Disable memif if queue spread by default

- calico-vpp-agent/cni/cni_server.go
- calico-vpp-agent/cni/network_vpp_hostports.go
- calico-vpp-agent/cni/storage/storage.go
- calico-vpp-agent/policy/policy_server.go
Some Calico CI failures are probably because we miss support for V6 hostports.
A hostport pod is a pod that is exposed on a port on its host node.
This patch adds the support for an ipv6 hostIP address in a hostport, or fallbacking to the nodes ip addresses (including v6 as well) if none is specified.
We only do v4 to v4 and v6 to v6 when we NAT.
This was tested manually, and should be covered by some Calico CI tests.
> Support v6 hostport

- .ci/Dockerfile.depend
- .ci/Makefile
- .ci/common.mk
- calico-vpp-agent/Makefile
- calico-vpp-agent/cni/network_vpp_routes.go
- config/config.go
- go.mod
- vpp-manager/vpp_runner.go
- vpplink/neighbor.go
- vpplink/routes.go
- vpplink/types/neigh.go
This patch enables IP neighbor aeging in VPP, defaulting to a 30sec
renewal. IP neighbors older than 30s will trigger an ARP request
or be retired.
This patch also marks the static neighbors we require as static so
that they are not subject to aeging.
This addresses an issue in Cloud environment where nodes or peer VMs
are recreated, keeping the same IP but changing the associated MAC
without triggering a gratuitous ARP. When this happens, VPP keeps the
old MAC entry indefinitely and traffic to said node is blackholed.
This can be configured using
```
CALICOVPP_INITIAL_CONFIG={
"ip4NeighborsMaxNumber": 50000,
"ip6NeighborsMaxNumber": 50000,
"ip4NeighborsMaxAge": 30,
"ip6NeighborsMaxAge": 30
}
```
> Add IP neighbor 30s aging v3.26.2-rc0

- calico-vpp-agent/cni/network_vpp_routes.go
- calico-vpp-agent/cni/storage/storage.go
This patch addresses an issue where upon dataplane restart a pod with PBL enabled would find itself with multiple PBL instances as we did use a list and did not check for existing entries on recreation.
This patch solves this using a single entry per pod while waiting for a proper refactoring.
> use single pbl index per pod

- .gitignore
- vpp-manager/Makefile
This patch addresses the fact that the VPP_HASH computation did not contain the list of deb files included within the VPP build cache. As a consequence, expanding this list, e.g. when added extra deps breaks the build.
This patch addresses this by making the deb list being part of the VPP_HASH computation.
This also enables the tar.gz computation when running locally, that way if the vpp_clone_current.sh has not changed, we won't rebuild VPP
> Fix makefile VPP_HASH cache invalidation

- calico-vpp-agent/prometheus/prometheus.go
- calico-vpp-agent/prometheus/stats_description.go
This patch fixes an issue where the stats of multiple interfaces with the same name would overlap and we would only be reporting a single entry.
Additionnally, due to a locking.Unlock issue we would stop reporting stats if an error occured.
> Fix prom stats overlap & RC

- Makefile
- cmd/calicovppctl/main.go
- go.mod
- go.sum
[CALICOVPP-9] This converts vppdev.sh to a Go binary to leverage Golang APIs.
Placed it under an "util" folder.
"make util" creates the "calivppctl" Go executable under util/bin/ directory.
Usage:
- **calivppctl vppctl [NODENAME]**                                 - Get a vppctl shell on a specific node
- **calivppctl log [-f] [-vpp|-agent|-felix] [NODENAME]** - Get the logs of vpp (dataplane) or agent (controlplane) or felix daemon
- **calivppctl clear**                                                           - Clear vpp internal stats
- **calivppctl export**                                                        - Create an archive with vpp & k8 system state for debugging.
- **calivppctl exportnode [NODENAME]**                        - Create an archive with vpp & k8 system state for a …
> convert vppdev.sh to Go binary

- Makefile
- vpp-manager/Makefile
In the CI we were wrongly computing the hash of the tarball name containing the VPP build artifacts, 
as we included the path of the debs.
This patch addresses this issue and should restore the VPP tarball caching in CI.
> Fix CI vpp tarball caching issue

- Makefile
- test/kind/Makefile
- test/kind/install_calico_vpp.sh
- test/kind/new_cluster.sh
This patch adds a 'make kind' directive that spins up a kind cluster, 
installs Calico, CalicoVPP from a local build VPP and the agent.
> Add make-kind directive

- vpplink/generated/generate.log
- vpplink/generated/vpp_clone_current.sh
This patch cherry-picks the following VPP fixes that addressed some VCL issues related to UDP & TCP session establishement.
- 43107: vcl: fix fifo private vpp sh on migration | https://gerrit.fd.io/r/c/vpp/+/43107
- 43714: session: fix handling of closed during migration | https://gerrit.fd.io/r/c/vpp/+/43714
- 43139: udp: regrab connected session after transport clone | https://gerrit.fd.io/r/c/vpp/+/43139
- 43723: session svm: fix session migrate attach data corruption | https://gerrit.fd.io/r/c/vpp/+/43723
> [release/v3.29] Cherry pick hoststack patches fixing session reuse

- .gitignore
- Makefile
- common.mk
- docs/developper_guide.md
- test/kind/Makefile
- test/kind/new_cluster.sh
- test/scripts/cases_util.sh
- test/scripts/ci_util.sh
- test/scripts/mngmt.sh
- test/scripts/provision.sh
- test/scripts/shared.sh
- test/scripts/test.sh
- yaml/overlays/dev/kustomize.sh
This patch allows to use multiple clusters on the same machine.
It names each cluster 'kind-(whoami)-(repohash)' and uses <repo>/.tmp/ to
store the calico-vpp.yaml and other installation scripts
> User-local kind cluster
