projectcalico/vpp-dataplane

vpp-manager/images/ubuntu/Dockerfile
=> Add iproute2 to vpp-manager image

go.mod
=> Update lunixbochs/struc to include patch

go.sum, vpp-manager/main.go, vpplink/binapi/generate_binapi.sh
=> Fix generate_binapi script & go.sum

calico-vpp-agent/config/config.go, vpp-manager/main.go
=> Change default RX mode to adaptive

vpp-manager/images/ubuntu/Dockerfile, vpplink/binapi/vpp_clone_current.sh
=> Update to calico_plugin:15

test/scripts/cases.sh, test/scripts/cases_util.sh
=> Cleanup baremetal specific CI scripts

vpp-manager/main.go, vpplink/addr.go, vpplink/routes.go, vpplink/types/addr.go, vpplink/types/route.go
Default route wasn't correctly propagated to vpp in vpp-manager
=> Fix passing default route to vpp

vpp-manager/main.go
We need to be careful at cleanup, as if the driver swap happens while vpp is still running, vpp & vpp-manager end up competing and eventually wait for the driver to be released.
=> Fix swap driver cleanup causing process lock

vpp-manager/images/dev/Dockerfile, vpp-manager/images/dev/entrypoint.sh, vpp-manager/images/dev/vpp.sh, vpp-manager/images/dev/vppctl.sh, vpp-manager/main.go
#26 was actually caused by the bash script for vpp not forwarding the signals
Also revert the modification that prevents the restore of the linux config
=> Fix vpp-manager conf restore & vpp process lock

test/baremetal/orch.sh, test/scripts/cases.sh, test/scripts/cases_util.sh, test/scripts/ci.sh, test/scripts/ci_util.sh, test/scripts/shared.sh, vpp-manager/main.go
=> Fix vpp-manager & clean snat/nodeport tests

vpp-manager/main.go
=> Only add v6 addr + route for non /128 ll addresses

calico-vpp-agent/routing/bgp_watcher.go, calico-vpp-agent/routing/connectivity/ipsec.go, calico-vpp-agent/routing/nodes_watcher.go, vpp-manager/main.go, vpp-manager/pool_sync.go, vpplink/helpers.go, vpplink/routes.go, vpplink/types/route.go
=> Fix ipsec & ipip v6 support

calico-vpp-agent/cni/network_vpp.go, calico-vpp-agent/config/config.go, vpp-manager/interface_config.go, vpp-manager/main.go, vpp-manager/pool_sync.go
=> Use tun instead of tap interfaces

vpplink/binapi/vpp_clone_current.sh, vpplink/binapi/vppapi/generate.log
Add https://gerrit.fd.io/r/c/vpp/+/28711 that fixes af_xdp interrupt mode
=> Add vpp interrupt patch

test/baremetal/provision.sh, yaml/overlays/dev/kustomize.sh
Handles if `/tmp/calico-vpp.yaml` exists and was created by another user
=> Allow for existing config files in orch.sh

yaml/overlays/af-packet/af-packet.yaml, yaml/overlays/af-packet/kustomization.yaml, yaml/overlays/af-xdp/af-packet.yaml, yaml/overlays/af-xdp/kustomization.yaml
=> Add kustomize for af_packet & af_xdp

test/baremetal/provision.sh, vpp-manager/Makefile, yaml/overlays/dev/kustomize.sh
=> Revert missing IMAGE_DIR

test/scripts/perftest/monit/test.yaml, test/scripts/shared.sh, test/scripts/test.sh, test/scripts/vppdev.sh
=> test: Add memory tracking & iperf runner

vpplink/binapi/vpp_clone_current.sh, vpplink/binapi/vppapi/generate.log, vpplink/binapi/vppapi/ip/ip.ba.go, vpplink/binapi/vppapi/mfib_types/mfib_types.ba.go, vpplink/binapi/vppapi/nat/nat.ba.go, vpplink/binapi/vppapi/nat/nat_rpc.ba.go
=> Bump VPP version

calico-vpp-agent/cni/cni_server.go, vpp-manager/Makefile, vpp-manager/images/ubuntu-build/build_script.sh, vpp-manager/images/ubuntu/Dockerfile, vpplink/binapi/vpp_clone_current.sh
- Debug symbols
- lock for CNI server
- cnat fix
=> agent: backport fixes to release/0.8.2

calico-vpp-agent/config/config.go
=> agent: Default to GSO on

calico-vpp-agent/Makefile, vpp-manager/Makefile
=> build: dont --pull in dev due to docker limit

calico-vpp-agent/Dockerfile
=> agent: find isnt installed in image

calico-vpp-agent/config/config.go, vpp-manager/startup/startup.go
=> agent/vpp-manager : add warning when unsupported env vars are detected

calico-vpp-agent/cni/network_vpp.go
=> agent: fix rx placement issue with no wrk

yaml/base/calico-vpp.yaml, yaml/overlays/dev/calicodev.yaml
=> yaml: Fix for containerd.io support

Makefile, yaml/overlays/dev/kustomize.sh
=> make: Add scripts for containerd / k3s

vpp-manager/uplink/common.go, vpp-manager/uplink/dpdk.go, vpp-manager/vpp_runner.go
=> vpp: Add dpdk uplink driver

vpp-manager/startup/interface_config.go
=> manager: fix linux config load

vpplink/binapi/vpp_clone_current.sh, vpplink/binapi/vppapi/generate.log, vpplink/binapi/vppapi/ikev2/ikev2.ba.go, vpplink/binapi/vppapi/ikev2_types/ikev2_types.ba.go, vpplink/binapi/vppapi/ip/ip.ba.go, vpplink/binapi/vppapi/ip/ip_rpc.ba.go
* Fixes af_packet stalling when exceeding ringbuffers
* Integrate merged patches
=> vpp: Add af-packet fix & bump master

yaml/base/calico-vpp.yaml, yaml/overlays/dev/kustomize.sh, yaml/overlays/dpdk/dpdk.yaml, yaml/overlays/eks-dpdk/eks-config.yaml
=> yaml: disable ping plugin by default

vpp-manager/config/config.go, vpp-manager/uplink/af_packet.go, vpp-manager/uplink/af_xdp.go, vpp-manager/uplink/avf.go, vpp-manager/uplink/common.go, vpp-manager/uplink/default.go, vpp-manager/uplink/dpdk.go, vpp-manager/uplink/virtio.go, vpp-manager/utils/utils.go, vpp-manager/vpp_runner.go, vpplink/binapi/vpp_clone_current.sh, vpplink/binapi/vppapi/generate.log, vpplink/binapi/vppapi/interface/interface.ba.go, vpplink/binapi/vppapi/interface/interface_rpc.ba.go, vpplink/interfaces.go
=> vpp-manager: rm phy routes&addr before vpp

go.mod, go.sum, vpplink/binapi/vpp_clone_current.sh, vpplink/binapi/vppapi/generate.log, vpplink/binapi/vppapi/ip/ip.ba.go, vpplink/binapi/vppapi/vpe_types/vpe_types.ba.go
=> vpp: Integrate enumflag fix

vpp-manager/uplink/af_xdp.go
=> vpp-manager: af_xdp queue error default

vpplink/binapi/vpp_clone_current.sh, vpplink/binapi/vppapi/af_packet/af_packet.ba.go, vpplink/binapi/vppapi/af_xdp/af_xdp.ba.go, vpplink/binapi/vppapi/avf/avf.ba.go, vpplink/binapi/vppapi/cnat/cnat.ba.go, vpplink/binapi/vppapi/feature/feature.ba.go, vpplink/binapi/vppapi/generate.log, vpplink/binapi/vppapi/gso/gso.ba.go, vpplink/binapi/vppapi/ikev2/ikev2.ba.go, vpplink/binapi/vppapi/interface/interface.ba.go, vpplink/binapi/vppapi/interface_types/interface_types.ba.go, vpplink/binapi/vppapi/ip/ip.ba.go, vpplink/binapi/vppapi/ip6_nd/ip6_nd.ba.go, vpplink/binapi/vppapi/ip_neighbor/ip_neighbor.ba.go, vpplink/binapi/vppapi/ipip/ipip.ba.go, vpplink/binapi/vppapi/ipsec/ipsec.ba.go, vpplink/binapi/vppapi/ipsec/ipsec_rpc.ba.go, vpplink/binapi/vppapi/ipsec_types/ipsec_types.ba.go, vpplink/binapi/vppapi/nat44/nat44.ba.go, vpplink/binapi/vppapi/nat44/nat44_rpc.ba.go, vpplink/binapi/vppapi/tapv2/tapv2.ba.go, vpplink/binapi/vppapi/tunnel_types/tunnel_types.ba.go, vpplink/binapi/vppapi/virtio/virtio.ba.go, vpplink/binapi/vppapi/vxlan/vxlan.ba.go, vpplink/binapi/vppapi/wireguard/wireguard.ba.go, yaml/base/calico-vpp.yaml, yaml/overlays/dev/kustomize.sh, yaml/overlays/dpdk/dpdk.yaml, yaml/overlays/eks-dpdk/eks-config.yaml
Updates the cnat snat policy. Fixes ikev2 setup & VPP ping_plugin
=> Bump vpp version (ping & ikev2 issues)

vpplink/binapi/vpp_clone_current.sh, vpplink/binapi/vppapi/generate.log
=> vpp: Add dpdk-interrupt patch

vpp-manager/images/ubuntu/Dockerfile, vpplink/binapi/vpp_clone_current.sh, vpplink/binapi/vppapi/generate.log
=> vpp: fix missing dep + dpdk ena

vpplink/binapi/vpp_clone_current.sh
=> vpp: bump maglev/fixes

go.mod, go.sum
This PR want to upgrade gobgp to the latest version  (v2.25.0) as mentioned in #141
=> upgrade gobgp to latest version

vpp-manager/uplink/af_packet.go, vpp-manager/uplink/af_xdp.go, vpp-manager/uplink/avf.go, vpp-manager/uplink/common.go
=> vpp-manager: Fix avf NS for PF

vpplink/cnat.go
=> vpplink: Fix dumb for snat allowlist

vpp-manager/config/config.go, vpp-manager/vpp_runner.go
=> vpp-manager: Fix vpptap0 mtu

vpp-manager/vpp_runner.go
=> vpp-manager: Fix vpptap0 mtu (again)

vpplink/types/wireguard.go
=> vpplink: Fix WG typo

test/scripts/vppdev.sh, vpplink/cnat.go
=> Some nitfixes

vpp-manager/link_watcher.go, vpp-manager/route_watcher.go
=> vpp-manager: Fix link watcher on teardown

vpp-manager/Makefile
=> vpp-manager: Also build eks-init by default

vpplink/binapi/vpp_clone_current.sh, vpplink/binapi/vppapi/generate.log
=> vpp: integrate virtio fixes

vpplink/binapi/generate_binapi.sh, vpplink/binapi/vpp_clone_current.sh, vpplink/binapi/vppapi/generate.log
=> vpp: integrate cnat fix

calico-vpp-agent/routing/connectivity/ipsec.go
This workaround ikev2 failing to initiate the tunnel (e.g. because of packet drop, RC, ...)
And retries initiating the tunnel while waiting for the interface to be up
=> agent: retry ipsec initiate in wait loop

scripts/create_eks_cluster.sh
EC2 launch template accepts an empty KeyName field but the nodegroup
creation does not like it. This causes nodegroup creation to fail when
KEYNAME or -k <keyname> option is not specified. Fix prevents empty
KeyName field in the launch template.
=> create_eks_cluster.sh: fix empty KeyName field error

go.mod, go.sum
=> build: fix make gobgp

calico-vpp-agent/cni/network_vpp.go, vpp-manager/config/config.go, vpp-manager/vpp_runner.go, vpplink/interfaces.go
Default MTU is 9000 which is too low
=> cni: set tun mtu

test/scripts/kubeadm/ClusterJoinConfiguration.template.yaml, test/scripts/kubeadm/ClusterNewConfiguration.template.yaml, test/scripts/provision.sh, test/scripts/test.sh, test/yaml/Makefile, test/yaml/iperf/test.yaml, test/yaml/iperf/test_single.yaml, test/yaml/iperf3-vcl/Dockerfile, test/yaml/iperf3-vcl/iperf3-tls-vcl.sh, test/yaml/iperf3-vcl/iperf3-vcl.sh, test/yaml/iperf3-vcl/test.yaml, test/yaml/nginx/test.yaml, test/yaml/scalepods/test.yaml, test/yaml/testpmd/Dockerfile, test/yaml/testpmd/memif-testpmd.sh, test/yaml/testpmd/patches/0000-memif-abstract-fix.patch, test/yaml/testpmd/test.yaml, test/yaml/wrk/Dockerfile, test/yaml/wrk/patches/0001-no-keepalive-option.patch, test/yaml/wrk/test.yaml, test/yaml/wrk/wrk.py
=> test: Update for k8s 1.22.1 & VCL/memif

calico-vpp-agent/policy/policy_server.go, calico-vpp-agent/policy/workload_endpoint.go, calico-vpp-agent/routing/connectivity/ipip.go, calico-vpp-agent/routing/connectivity/ipsec.go, calico-vpp-agent/routing/connectivity/vxlan.go, calico-vpp-agent/routing/connectivity/wireguard.go, calico-vpp-agent/routing/watchers/ipam.go, calico-vpp-agent/services/service_handler.go, vpp-manager/uplink/default.go, vpp-manager/uplink/dpdk.go
=> agent: nitfixes, logging & del issue

test/yaml/Makefile, test/yaml/testpmd/memif-testpmd.sh, test/yaml/trex/Dockerfile, test/yaml/trex/README.md, test/yaml/trex/build.Dockerfile, test/yaml/trex/build_script.sh, test/yaml/trex/patches/0000-memif-abstract-trex.patch, test/yaml/trex/test.yaml, test/yaml/trex/trex-console.sh, test/yaml/trex/trex-start.sh, test/yaml/trex/trex_template.py
=> test: Add trex yaml

test/vagrant/Makefile, test/vagrant/vagrantfiles/Vagrantfile_common
- vagrant: bump k8s to 1.22.1
- vagrant: switch runtime to containerd
=> Vagrant env upgrade

vpplink/binapi/vpp_clone_current.sh, vpplink/binapi/vppapi/acl/acl.ba.go, vpplink/binapi/vppapi/acl/acl_rpc.ba.go, vpplink/binapi/vppapi/generate.log, vpplink/binapi/vppapi/interface/interface.ba.go, vpplink/binapi/vppapi/interface/interface_rpc.ba.go, vpplink/binapi/vppapi/session/session.ba.go, vpplink/binapi/vppapi/session/session_rpc.ba.go
=> vpp: Bump merged patches

test/scripts/kubeadm/ClusterJoinConfiguration.template.yaml, test/scripts/kubeadm/ClusterNewConfiguration.template.yaml, test/scripts/provision.sh, yaml/overlays/dev/calico-node-dev-patch.yaml, yaml/overlays/dev/kustomize.sh
=> test: update cluster provisioning for ipV6

vpplink/binapi/vpp_clone_current.sh, vpplink/binapi/vppapi/generate.log, vpplink/binapi/vppapi/ip/ip.ba.go, vpplink/binapi/vppapi/ip/ip_rpc.ba.go
=> vpp: Bump to master

calico-vpp-agent/cni/cni_server.go, calico-vpp-agent/cni/network_vpp.go, calico-vpp-agent/cni/network_vpp_routes.go, calico-vpp-agent/cni/pod_interface/common.go, calico-vpp-agent/cni/pod_interface/loopback.go, calico-vpp-agent/cni/storage/storage.go, vpplink/binapi/vppapi/generate.log, vpplink/ip.go
=> cni: dynamicaly allocate VRFs

vpplink/binapi/vpp_clone_current.sh, vpplink/binapi/vppapi/af_packet/af_packet.ba.go, vpplink/binapi/vppapi/generate.log, vpplink/binapi/vppapi/nat44_ed/nat44_ed.ba.go, vpplink/binapi/vppapi/nat44_ed/nat44_ed_rpc.ba.go, vpplink/binapi/vppapi/session/session.ba.go, vpplink/binapi/vppapi/session/session_rpc.ba.go
=> vpp: Bump w/ fib patches

vpp-manager/images/dev/vpp.sh, vpp-manager/images/dev/vppctl.sh, vpp-manager/startup/startup.go
- manager: remove unnecessary log with no extra interfaces configured
- images: fix dev images library path
=> Minor fixes

calico-vpp-agent/cmd/calico_vpp_dataplane.go, calico-vpp-agent/cni/network_vpp_routes.go, calico-vpp-agent/cni/pod_interface/loopback.go, calico-vpp-agent/common/common.go, calico-vpp-agent/config/config.go, vpp-manager/config/config.go, vpp-manager/config/config_test.go, vpp-manager/pool_sync.go, vpp-manager/vpp_runner.go, vpplink/memif.go, vpplink/routes.go
This should fix #257 and also improve the behavior with multiple
interfaces as the broadcasts will now be sent on the uplink matching the
interface linux used.
=> Fix host trafic routing

vpplink/binapi/vpp_clone_current.sh, vpplink/binapi/vppapi/generate.log
=> vpp: integrate af_packet fix

calico-vpp-agent/cni/network_vpp_hostports.go
=> agent: fix hostport on error

vpp-manager/route_watcher.go
As route.Dst is a pointer, when in dual stack, we create v4/v6 mixed routes which
netlink lib doesn't like
=> vpp-manager: fix route watcher dual stack

calico-vpp-agent/policy/policy_server.go
=> agent: fix missing event hdl for policies server

vpplink/binapi/vpp_clone_current.sh, vpplink/binapi/vppapi/generate.log
=> vpp: integrate cnat rsession fix patch

calico-vpp-agent/routing/routing_server.go, calico-vpp-agent/watchers/ipam.go
=> agent: Fix ipam state

calico-vpp-agent/cni/cni_server.go, calico-vpp-agent/cni/network_vpp_hostports.go, calico-vpp-agent/cni/storage/storage.go
=> agent: improve hostports support

calico-vpp-agent/cmd/calico_vpp_dataplane.go, calico-vpp-agent/watchers/ipam.go
=> agent: Nitfixes

vpplink/binapi/vpp_clone_current.sh, vpplink/binapi/vppapi/generate.log, vpplink/binapi/vppapi/ip/ip.ba.go, vpplink/binapi/vppapi/ip/ip_rpc.ba.go, vpplink/binapi/vppapi/wireguard/wireguard.ba.go, vpplink/binapi/vppapi/wireguard/wireguard_rpc.ba.go
=> vpp: add memif underflow fix

test/scripts/mngmt.sh, vpp-manager/images/ubuntu-build/Dockerfile
=> images: Fix build & better push script

test/yaml/mvpp/README.md, test/yaml/mvpp/test.yaml
=> test: VPP+memif README

test/policies/ds.yaml, vpp-manager/Makefile, vpp-manager/uplink/dpdk.go, vpp-manager/uplink/virtio.go, vpplink/binapi/vpp_clone_current.sh, vpplink/binapi/vppapi/generate.log, vpplink/vxlan.go, yaml/generated/calico-vpp-dpdk.yaml, yaml/generated/calico-vpp-eks-dpdk.yaml, yaml/overlays/dpdk/dpdk.yaml, yaml/overlays/eks-dpdk/eks-config.yaml
- yaml: update dpdk manifests to use dpdk built-in driver
- manager: tweaks to dpdk driver
=> Fix DPDK manifests

calico-vpp-agent/cni/cni_server.go, calico-vpp-agent/cni/network_vpp.go
We used not to re-increment the number of available buffers when a tap interface was deleted. This fixes that.
=> cni: fix buffer accounting

vpplink/binapi/vpp_clone_current.sh, vpplink/binapi/vppapi/generate.log
=> vpp: af-pkt fix kick

vpp-manager/config/config.go, vpp-manager/uplink/avf.go
=> vpp-manager: add ice in avf drivers

calico-vpp-agent/cni/pod_interface/memif.go, calico-vpp-agent/cni/pod_interface/tuntap.go
=> agent: fix isL3 routes

calico-vpp-agent/services/service_handler.go
=> agent: fix svc del

vpplink/types/capo.go
=> agent: Fix capo ipport type

calico-vpp-agent/connectivity/connectivity.go, calico-vpp-agent/connectivity/connectivity_server.go, calico-vpp-agent/connectivity/flat.go, calico-vpp-agent/connectivity/ipip.go, calico-vpp-agent/connectivity/ipsec.go, calico-vpp-agent/connectivity/srv6.go, calico-vpp-agent/connectivity/vxlan.go, calico-vpp-agent/connectivity/wireguard.go
=> agent: enable WG per node disabling

calico-vpp-agent/policy/policy_server.go, calico-vpp-agent/watchers/nodes_watcher.go, vpp-manager/main.go, vpp-manager/vpp_runner.go
=> agent: small log improvement

calico-vpp-agent/cni/cni_server.go, calico-vpp-agent/cni/network_vpp.go, calico-vpp-agent/connectivity/ipsec.go, calico-vpp-agent/policy/policy_server.go, calico-vpp-agent/watchers/ipam.go, calico-vpp-agent/watchers/nodes_watcher.go, calico-vpp-agent/watchers/peers_watcher.go, vpp-manager/main.go, vpp-manager/pool_sync.go, vpp-manager/uplink/common.go, vpp-manager/utils/utils.go, vpp-manager/vpp_runner.go
=> agent: log nitfixes

vpp-manager/main.go
=> vpp-manager: log/clean coredump for each VPP run

vpp-manager/uplink/dpdk.go, vpplink/binapi/vpp_clone_current.sh, vpplink/binapi/vppapi/generate.log
=> vpp: tag dpdk interfaces like other if types

calico-vpp-agent/cni/network_vpp.go
We were not removing the local state when removing
interfaces with conflicting IP addresses, thus still
removing the routes on delete. This fixes it, also
prevent deletion when the VRF is not found in VPP,
preventing leftover state to impact existing pods.
=> agent: remove pod from state on conficts

calico-vpp-agent/connectivity/ipsec.go
=> agent: re-order ipsec profile/swif binding

calico-vpp-agent/connectivity/ipsec.go
This patch introduces a cancel call for the goroutine checking
the tunnel's status in case it gets deleted.
It also make the ipsec connectivity leverage the cleanup stack
in case of add failures
=> agent: improve ipsec, cancel goroutines

.gitignore, test/scripts/mngmt.sh
=> automation: Add build reports

calico-vpp-agent/policy/rule.go
This was wronfully introduced by #327
=> agent: rollback policy wrong commit

calico-vpp-agent/cni/cni_server.go, calico-vpp-agent/cni/pod_interface/tuntap.go, calico-vpp-agent/watchers/ipam.go
This patch deduces the default MTU to use in pods
from the felix configuration, taking into account
updates that were not well propagated to the cni_server
object. It also takes into account the ippools present
when they have ipip or vxlan enabled, as this is not
reflected in the felixconfiguration.
On updates, the pods are also walked and their interface MTUs
are updated.
=> agent: deduce mtu from felix+ipam & update in pods

calico-vpp-agent/policy/host_endpoint.go, calico-vpp-agent/policy/policy.go, calico-vpp-agent/policy/policy_server.go, calico-vpp-agent/policy/rule.go, vpplink/types/capo.go
=> agent: Fix host endpoint policy delete

go.mod, go.sum
=> gomod: Clean projectcalico/calico autogen semver

calico-vpp-agent/proto/Makefile, calico-vpp-agent/proto/readme.md, vpp-manager/Makefile
=> agent: document version upgrade process

calico-vpp-agent/cni/cni_pod_test.go, calico-vpp-agent/cni/pod_interface/common.go, calico-vpp-agent/cni/pod_interface/loopback.go, calico-vpp-agent/cni/pod_interface/memif.go, calico-vpp-agent/cni/pod_interface/tuntap.go, calico-vpp-agent/cni/pod_interface/vcl.go, vpplink/memif.go, vpplink/types/memif.go
It is an integration test similar to the already existing one testing primary TAP tunnel.
=> Test for configuration of secondary memif tunnel to pod 

calico-vpp-agent/cni/cni_node_test.go, calico-vpp-agent/cni/cni_pod_test.go, calico-vpp-agent/cni/cni_server.go
Also enhanced older pod addition tests by adding checks for tunnel interfaces inside pods.
=> Test for configuration of multinet tunnel to pod

Makefile, vpp-manager/images/dev/entrypoint.sh, vpp-manager/images/dev/vpp.sh, vpp-manager/images/dev/vppctl.sh, yaml/overlays/dev/calico-vpp-daemonset-dev-patch.yaml, yaml/overlays/dev/kustomize.sh
=> target local build in kind-dev setup

DEVELOPPER_GUIDE.md, README.md
=> add developper guide

vpplink/binapi/vpp_clone_current.sh, vpplink/binapi/vppapi/generate.log
=> vpp: add dpdk interrupt mode fix

yaml/overlays/dev/kustomize.sh
Minor change for Installation config.
=> Set encapsulation for IPv6

calico-vpp-agent/cmd/calico_vpp_dataplane.go, calico-vpp-agent/cni/cni_server.go
Reduce warning level reported in the agent logs
=> agent: Reduce log level

scripts/init_eks.sh
Commenting out the unnecessary building of igb_uio in EKS
=> misc: cleanup init_eks.sh script

calico-vpp-agent/cni/pod_annotations.go, vpp-manager/vpp_runner.go
=> linter: fix for codeQL

test/yaml/iperf3/test.yaml, vpplink/binapi/vpp_clone_current.sh, vpplink/binapi/vppapi/generate.log
=> Add SCTP support

calico-vpp-agent/config/config.go, calico-vpp-agent/routing/common/common.go, calico-vpp-agent/routing/routing_server.go, calico-vpp-agent/routing/routing_server_init.go, calico-vpp-agent/routing/watchers/nodes_watcher.go
Fixes #461 
Signed-off-by: Pratik Raj <Rajpratik71@gmail.com>
=> routing: use node addresses for BGP listener fix for single stack system

calico-vpp-agent/watchers/peers_watcher.go, yaml/base/calico-vpp-daemonset.yaml, yaml/generated/calico-vpp-dpdk.yaml, yaml/generated/calico-vpp-eks-dpdk.yaml, yaml/generated/calico-vpp-eks.yaml, yaml/generated/calico-vpp-kind.yaml, yaml/generated/calico-vpp-nohuge.yaml, yaml/generated/calico-vpp.yaml
=> Release v3.24.1

config/startup/startup.go
=> vpp-manager: fix enable GSO by default

vpp-manager/images/ubuntu-build/Dockerfile
=> vpp: fix build dependancies in the build container

calico-vpp-agent/cmd/api-proxy/felix-api-proxy.go
This patch contains the final fixes for `golangci-lint run` to pass
=> fix: linting

calico-vpp-agent/cmd/watch_dog.go, calico-vpp-agent/cni/cni_server.go
=> agent: Reduce warnings at startup

calico-vpp-agent/policy/policy_server.go
new behavior is: we create a common ipset (as we use it in both endpointtohost and allowfromhost). When endpointtohostaction changes we create a rule with allow/deny targeting that ipset
=> agent: fix endpointtohostaction policy when set to accept

vpplink/binapi/patches/0001-pbl-Port-based-balancer.patch, vpplink/binapi/patches/0003-acl-acl-plugin-custom-policies.patch, vpplink/binapi/patches/0004-capo-Calico-Policies-plugin.patch
=> vpp: Silence capo warnings unless built so

calico-vpp-agent/policy/policy_server.go
=> agent: linter fixes

Makefile, calico-vpp-agent/cmd/calico_vpp_dataplane.go, calico-vpp-agent/common/pubsub.go, calico-vpp-agent/connectivity/connectivity_server.go, calico-vpp-agent/policy/policy_server.go, calico-vpp-agent/watchers/prefix_watcher.go, calico-vpp-agent/watchers/uplink_link_watcher.go, calico-vpp-agent/watchers/uplink_route_watcher.go, test/vagrant/Makefile
- agent: fix route watcher, improve logging
- agent: improve uplink link watcher logging
- connectivity: add debug log for ippool resolution
- make: fix calico installation
- vagrant: make Makefile faster
- agent: misc logging improvements
=> Host routing fix + misc changes

RELEASE_NOTES.md
=> Add 3.25 release notes

calico-vpp-agent/cmd/calico_vpp_dataplane.go, calico-vpp-agent/cni/cni_node_test.go, calico-vpp-agent/cni/cni_pod_test.go, calico-vpp-agent/common_tests/common_tests.go, calico-vpp-agent/policy/host_endpoint.go, calico-vpp-agent/policy/policy_server.go, calico-vpp-agent/watch_dog/watch_dog.go
this decouples parts of the integ tests, preparing for integrating policy fv tests
=> agent: refactor integration tests to include fv tests

calico-vpp-agent/cni/cni_pod_test.go, calico-vpp-agent/cni/netns_linux.go, calico-vpp-agent/cni/packet_helper.go, go.mod, go.sum
I hope it was what you expected me to do.
=> Add memif test in multinet

calico-vpp-agent/cmd/calico_vpp_dataplane.go, calico-vpp-agent/services/service_handler.go, calico-vpp-agent/watch_dog/watch_dog.go
=> Fixes for OpenShift support

yaml/platforms/openshift/00-namespace-calico-vpp-dataplane.yaml, yaml/platforms/openshift/01-cr-installation.yaml, yaml/platforms/openshift/03-configmap-calico-vpp-resources.yaml, yaml/platforms/openshift/03-role-calico-vpp-dataplane.yaml, yaml/platforms/openshift/03-rolebinding-calico-vpp-dataplane.yaml, yaml/platforms/openshift/03-serviceaccount-calico-vpp-dataplane.yaml, yaml/platforms/openshift/04-calico-vpp-nohuge.yaml
The manifest yamls required for openshift integration
=> yamls for openshift integration

calico-vpp-agent/cmd/calico_vpp_dataplane.go
This reverts commit 65afb871fbfdbb36fb4d31956d7f5a4dc2018afb.
=> Revert "ci debugger"

yaml/overlays/test-vagrant-srv6/srv6.yaml
=> Corrected Json section

calico-vpp-agent/watchers/uplink_link_watcher.go
`v` variable is not getting updated this way
=> silly error in link watcher

Makefile, docs/kind.md
The issue on multus master was fixed, so we can use it again
=> revert multus version fix

yaml/generated/calico-vpp-dpdk.yaml, yaml/generated/calico-vpp-eks-dpdk.yaml, yaml/generated/calico-vpp-eks.yaml, yaml/generated/calico-vpp-kind-multinet.yaml, yaml/generated/calico-vpp-kind.yaml, yaml/generated/calico-vpp-multinet.yaml, yaml/generated/calico-vpp-nohuge.yaml, yaml/generated/calico-vpp.yaml
=> yaml: update image tags to latest

docs/bgp_filtering.md, docs/memif.md, docs/vcl.md, test/yaml/bgp/bgpFilter.yaml, test/yaml/bgp/externalBgpPeer.yaml, test/yaml/mvpp/test.yaml
this adds details to some doc
and the way we configure an external bgp peer and a bgp filter and testing
=> fix some docs and add bgpfilter doc

calico-vpp-agent/cni/storage/storage.go, calico-vpp-agent/common_tests/common_tests.go
now they look like
```
[4] table_id:3519870697 WxSxK9ks-4-eth0-cni-58662c00-bb5a-024f-3a2a-3483ecab0cdd-
[5] table_id:1649599747 kQjV/vfh-4-eth0-cni-58662c00-bb5a-024f-3a2a-3483ecab0cdd-RPF
[6] table_id:1476291629 UPb6PJZ2-4-eth1-cni-58662c00-bb5a-024f-3a2a-3483ecab0cdd-
[7] table_id:2180890343 G48PsJzB-4-eth1-cni-58662c00-bb5a-024f-3a2a-3483ecab0cdd-RPF
```
```
[8] table_id:2670642822 a3PhVMGj-6-eth0-cni-58662c00-bb5a-024f-3a2a-3483ecab0cdd-RPF
[9] table_id:2748932008 Kys2SUCl-6-eth1-cni-58662c00-bb5a-024f-3a2a-3483ecab0cdd-
[10] table_id:2498801434 CAjsgbRR-6-eth1-cni-58662c00-bb5a-024f-3a2a-3483ecab0cdd-RPF
[11] table_id:3167820124 ssXduxzE-6-eth0-cni-541c5a51-6301-39af-9532-e56db8abc4af-
```
=> agent: add rpf to rpf table tag

go.mod, go.sum, vpplink/generated/generate.log
=> update govpp dependancy

calico-vpp-agent/policy/policy_server.go
This patch adds support for setting the .net property when defining the failsafepolicies in felixconfig. This is a not so well documented feature that slipped through when aiming for feature parity.
For reference, here is the documentation for [0] felixconfig.
- setting failsafeInboundHostPorts to e.g. {Net: "10.0.0.0/24", ...} will add a filter for inbound packets for their source prefix to match 10.0.0/24.
- setting failsafeOutboundHostPorts to e.g. {Net: "20.0.0.0/24". ...} will add a filter for outbound packets for their destination prefix to match 20.0.0/24
[0] https://docs.tigera.io/calico/latest/reference/resources/felixconfig#spec
=> [backport 3.26] Support setting failsafepolicy net

calico-vpp-agent/policy/policy_server.go
This patch adds support for setting the .net property when defining the failsafepolicies in felixconfig. This is a not so well documented feature that slipped through when aiming for feature parity.
For reference, here is the documentation for [0] felixconfig.
- setting failsafeInboundHostPorts to e.g. {Net: "10.0.0.0/24", ...} will add a filter for inbound packets for their source prefix to match 10.0.0/24.
- setting failsafeOutboundHostPorts to e.g. {Net: "20.0.0.0/24". ...} will add a filter for outbound packets for their destination prefix to match 20.0.0/24
[0] https://docs.tigera.io/calico/latest/reference/resources/felixconfig#spec
=> [backport 3.27] Support setting failsafepolicy net

docs/prometheus.md
Doc describing how to check prometheus functionality
=> docs: prometheus howto

.ci/buildspec.yml, Makefile, vpp-manager/Makefile, vpp-manager/images/ubuntu-build/build_script.sh, vpplink/generated/vpp_clone_current.sh
Made 'make clean-vpp' explicit, 'make cherry-wipe' wasn't deleting the cache so I added a new path. Also added https_proxy vars to some docker build commands as I had issues when they were missing.
=> allow running 'make vpp' from an arbitrary directory

calico-vpp-agent/policy/policy_server.go
This patch adds support for setting the .net property when defining the failsafepolicies in felixconfig. This is a not so well documented feature that slipped through when aiming for feature parity.
For reference, here is the documentation for [0] felixconfig.
- setting failsafeInboundHostPorts to e.g. {Net: "10.0.0.0/24", ...} will add a filter for inbound packets for their source prefix to match 10.0.0/24.
- setting failsafeOutboundHostPorts to e.g. {Net: "20.0.0.0/24". ...} will add a filter for outbound packets for their destination prefix to match 20.0.0/24
[0] https://docs.tigera.io/calico/latest/reference/resources/felixconfig#spec
=> Support setting failsafepolicy net

calico-vpp-agent/prometheus/prometheus.go
This patch fixes an issue where the stats of multiple interfaces with the same name 
would overlap and we would only be reporting a single entry.
Additionnally, due to a locking.Unlock issue we would stop reporting stats if an error occured.
As an example, we now see the following for a pod with a memif
```
root@kind-worker2:~#  curl localhost:8888/metrics 2>/dev/null | grep -v '#' | grep rx_bytes | grep memif
rx_bytes{namespace="mvpp",podInterfaceName="vpp/memif-eth0",podName="mvpp",vppInterfaceName="memif1013904223/0",worker="0"} 0
rx_bytes{namespace="mvpp",podInterfaceName="vpp/memif-eth0",podName="mvpp",vppInterfaceName="memif1013904223/0",worker="1"} 0
rx_bytes{namespace="mvpp",podInterfaceName="vpp/memif-eth0",podName="mvpp",vppInterfaceName="memif1013904223/0",worker="2"} 0
```
=> [release/3.26] Fix prom stats overlap & RC

calico-vpp-agent/prometheus/prometheus.go, config/config.go
add `vpp_` prefix to prometheus stats
=> add vpp prefix to prometheus stats
